### ISSUE TITLE
[Bug] In Linux always return the same value

### ISSUE THREAD

**Issue by gperdomor** [vapor/random#4]
When you execute the program multiple times, the result are the same in linux...

Example: [random.zip](https://github.com/vapor/random/files/907142/random.zip)

<img width="448" alt="screen shot 2017-04-07 at 10 19 31 pm" src="https://cloud.githubusercontent.com/assets/371939/24824405/cdb3aa26-1be0-11e7-84f2-a5dae5ec6ae1.png">

**Comment by tanner0101** [comment]
@gperdomor use `Crypto.Random` from vapor/crypto. These generators are pseudorandom and this should be expected afaik. 

https://github.com/vapor/crypto/blob/master/Sources/Crypto/Random/Random.swift
